Django_Pjt_2/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path('home/',views.home,name='home')
]

Django_Pjt_2/project02/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/', include('board.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Pjt_2/board/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)

    def __str__(self):
        return self.title

Django_Pjt_2/board/forms.py
from socket import fromshare
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade", 'imgfile']

Django_Pjt_2/board/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm

# Create your views here.
def index(request):
    review = Review.objects.order_by("-pk")
    context = {
        "review": review,
    }
    return render(request, "board/index.html", context)


def create(request):

    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect("board:index")
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }

    return render(request, "board/create.html", context=context)


def detail(request, pk):

    review = Review.objects.get(pk=pk)

    context = {
        "review": review,
    }

    return render(request, "board/detail.html", context)


def delete(request, pk):

    review = Review.objects.get(pk=pk)

    review.delete()

    return redirect("board:index")


def update(request, pk):

    if request.method == "POST":
        review = Review.objects.get(pk=pk)
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect("board:detail", pk)
    else:
        review = Review.objects.get(pk=pk)
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
    }

    return render(request, "board/update.html", context=context)


def home(request):
    return render(request,'board/home.html')

Django_Pjt_2/board/templates/board/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="container">
    <h1 class='text-center mb-4 fw-bold'>글작성 페이지</h1>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      {% bootstrap_form review_form %}
      <div class="d-grid gap-2">
        <input class="btn btn-primary" type="submit" value="작성">
      </div>
    </form>
  </div>
{% endblock %}>

Django_Pjt_2/board/templates/board/detail.html
{% extends 'base.html' %}

{% block content %}

  <div class="container py-5">
    <div class="card" style="width: auto;">
      <div class="card-body">
        <div>
          <h6 class='text-center text-secondary text-opacity-75'>리뷰 영화 제목</h6>
          <h1 class='text-center fw-semibold mb-2 text-white bg-secondary bg-opacity-100'>{{review.movie_name}}</h1>
          <p class="fs-6 text-end text-secondary text-opacity-75">평점:
            {{review.grade}}점</p>
        </div>
        <h3 class='mb-5 fs-2 fw-semibold'>
          {{review.title}}</h3>
        <p class='fs-6 text-info text-opacity-100 mb-5'>내용:
          {{review.content}}</p>
        <div class='d-flex justify-content-between'>
          <a class="btn btn-outline-primary w-40" href="{% url 'board:index' %}">목록</a>
          <div>
            <a class='btn btn-outline-success w-40' href="{% url 'board:update' review.pk %}">수정</a>
            <a class="btn btn-outline-danger w-40" href="{% url 'board:delete' review.pk %}">삭제</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Django_Pjt_2/board/templates/board/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div id="carouselExampleControls" class="carousel slide mb-5" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/spiderman.jpg' %}" class="d-block w-100 h-auto" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/topgun.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Nextt</span>
    </button>
  </div>
{% endblock %}

Django_Pjt_2/board/templates/board/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1 class='text-center mb-5 fw-bold'>영화 리뷰</h1>

    <table class="table table-hover mb-3">
      <thead>
        <tr>
          <th scope="col">PK</th>
          <th scope="col">영화 이름</th>
          <th scope="col">리뷰 제목</th>
          <th scope="col">평점</th>
          <th scope="col">글 작성 시간</th>

        </tr>
      </thead>
      <tbody>
        {% for r in review %}
          <tr onclick='location.href="{{ r.pk }}"' style='cursor: pointer;'>
            <td>{{ r.pk }}</td>
            <td>{{ r.movie_name }}</td>
            <td>{{ r.title }}</td>
            <td>{{ r.grade }}</td>
            <td>{{ r.updated_at }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <nav aria-label="Page navigation example ">
    <ul class="pagination  justify-content-center">
      <li class="page-item">
        <a class="page-link" href="{% url 'board:index' %}">이전</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">4</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">5</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">6</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">다음</a>
      </li>
    </ul>
  </nav>
{% endblock %}

Django_Pjt_2/board/templates/board/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}



<div class="container">
    <h1>수정 페이지</h1>
    <form action="" method="POST">
        {% csrf_token %}

        {% bootstrap_form review_form %}
        <div class="d-grid gap-2">
            <input class="btn btn-primary" type="submit" value="수정">
        </div>
    </form>
</div>
{% endblock %}>

Django_Pjt_2/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
  {% comment %} {% bootstrap_css %} {% endcomment %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-expand-lg sticky-top text-bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'board:home' %}"><img src="{% static 'img/logo.png' %}" style='height: 3rem' class='mb-2'></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">목록</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'board:create' %}">작성</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div  class='bg-light'>
      {% block content %}{% endblock %}
  </div>
  <!-- JavaScript Bundle with Popper -->
  {% comment %} {% bootstrap_javascript %} {% endcomment %}
  <footer class='sticky-bottom text-bg-light'>
    <div class="container py-2">
      <p class='text-center mb-0'>Created By 이동현, 조승윤, 이준엽</p>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
</body>

</html>